### ISSUE TITLE
Out Of Memory

### ISSUE THREAD

**Issue by dicheny** [tsinghua-fib-lab/moss#3]
Hello,

![1](https://github.com/user-attachments/assets/d4cdd5a2-1760-4156-9a9f-6a568059f2fa)

I want to know how much memory is needed to run demo，
Or maybe this is caused by a bug.

Best Wishes

**Comment by Sweetnow** [comment]
In the version v0.5.0, we add a automatic GPU memory preallocation mechanisim. Now you will have a parameter "device_mem" (unit: GiB) to set the preallocate GPU memory size. If you ignore the parameter, it will use 80% of the free memory on the device.

In the previous version, the size of preallocation is always 20GiB so that in some GPU you will see out of memory bug.
